version: "3.9"
services:
  bibigpt:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        IS_USED_SENTRY: 0
    container_name: bibigpt
    restart: unless-stopped
    ports:
      - "2014:3000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=1Panel-redis-1567
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis_hR5BcF
